- name: makesure we are using the OS packages for openswan
  apt: name=openswan state=present
- name: install lsof
  apt: name=lsof state=present
- name: set sysctl net.ipv4.ip_forward=1
  sysctl: name=net.ipv4.ip_forward value=1 state=present reload=yes
- name: set sysctl net.ipv4.conf.all.accept_redirects=0
  sysctl: name=net.ipv4.conf.all.accept_redirects value=0 state=present reload=yes
- name: set sysctl net.ipv4.conf.all.send_redirects=0
  sysctl: name=net.ipv4.conf.all.send_redirects value=0 state=present reload=yes
- name: copy /etc/ipsec.conf template
  template: src=etc/ipsec.conf.generic dest=/etc/ipsec.conf
- name: copy /etc/ipsec.secrets template
  template: src=etc/ipsec.secrets dest=/etc/ipsec.secrets
- name: "Restart ipsec"
  service: name=ipsec state=restarted

