Vagrant.configure("2") do |config|

  require 'yaml'
  require 'open3'

  vault_file = "~/dotfiles/ansible/group_vars/all/vaulted_secrets.yml"
  vault_password_file = "~/vault_pass.txt"

  cmd = "ansible-vault view "+vault_file+" --vault-password-file "+vault_password_file+"|cat"
  cmd_output = ""
  Open3.popen3(cmd) do |stdin, stdout, stderr, wait_thr|
    while line = stdout.gets
      cmd_output += line
    end
  end
  secret_config = YAML::load(cmd_output)
  
  config.vm.box = "dummy"
  config.vm.provider :aws do |aws, override|
    aws.access_key_id = secret_config['aws_access_key_id']
    aws.secret_access_key = secret_config['aws_secret_access_key']
    aws.region = "us-west-2"
    aws.instance_type = "t2.micro"
    aws.keypair_name = "ansible-child-key"
    aws.security_groups = ["wideopen"] #wide open everything
    aws.ami = "ami-3d50120d"
    #override.ssh.username = "ubuntu"
    #override.ssh.private_key_path = "PATH TO YOUR PRIVATE KEY"
  end
  config.ssh.username = "ubuntu"
  config.ssh.private_key_path= "/home/ubuntu/.ssh/id_rsa"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "/home/ubuntu/dotfiles/ansible/vagranttestsite.yml"
    ansible.vault_password_file = "/home/ubuntu/vault_pass.txt"
    ansible.groups = {
      "ataoeguests" => ["aoeguest"],
      "ataoeservers" => ["aoeserver"],
      "all_groups:children" => ["aoeguests","aoeservers"]
    }
  end
  config.vm.define "aoeserver" do |aoeserver|
    #aoeserver.vm.provision "ansible" do |ansible|
    #  ansible.playbook = ""
    #end
    aoeserver.vm.provider "aws" do |provider, override|
      provider.tags = {
        'Name' => 'aoeserver',
        'AnsiblePlaybooks'=>'aoeserver'
      }
    end
  end
  config.vm.define "aoeguest" do |aoeguest|
    aoeguest.vm.provider "aws" do |provider, override|
      provider.tags = {
        'Name' => 'aoeguest',
        'AnsiblePlaybooks'=>'aoeguest'
      }
    end
  end
end

