- name: make sure we are using the OS packages for vagrant
  apt: name=vagrant state=present
- name: make sure we are using the OS packages for ruby1.9.1-dev
  apt: name=ruby1.9.1-dev state=present
- name: install vagrant-aws plugin
  command: "vagrant plugin install vagrant-aws"
- name: install dummy box
  command: "vagrant box add dummy https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
