- apt: name=debootstrap state=present
- apt: name=nfs-kernel-server state=present
- file: path=/var/nfsroot state=directory mode=755
- file: path=/var/nfsroot/trusty-amd64 state=directory mode=755
- file: path=/var/lib/tftpboot/ubuntu-boot/trusty/amd64 state=directory mode=755
- template: src=etc/exports dest=/etc/exports mode=755
- command: /usr/sbin/exportfs -rv
#- command: /usr/sbin/debootstrap --arch=amd64 trusty /var/nfsroot/trusty-amd64
- command: /bin/mount -o bind /dev /var/nfsroot/trusty-amd64/dev
- command: /bin/mount -o bind /proc /var/nfsroot/trusty-amd64/proc
- command: /usr/sbin/chroot /var/nfsroot/trusty-amd64 apt-get update
- command: /usr/sbin/chroot /var/nfsroot/trusty-amd64 apt-get install -y linux-image-3.13.0-24-generic syslinux
- command: /bin/umount /var/nfsroot/trusty-amd64/dev
- command: /bin/umount /var/nfsroot/trusty-amd64/proc
- copy: src=/var/nfsroot/trusty-amd64/usr/lib/syslinux/pxelinux.0 dest=/var/lib/tftpboot/ubuntu-boot/trusty/amd64
- copy: src=/var/nfsroot/trusty-amd64/boot/vmlinuz-3.13.0-24-generic dest=/var/lib/tftpboot/ubuntu-boot/trusty/amd64
- copy: src=/var/nfsroot/trusty-amd64/boot/initrd.img-3.13.0-24-generic dest=/var/lib/tftpboot/ubuntu-boot/trusty/amd64
#- command: /usr/sbin/mkinitramfs -o /var/nfsroot/trusty-amd64/boot/initrd.img
# TODO download kernel
#- set_fact:
#    nginx_root: /usr/share/nginx/html
# probably more version dependent than distro
#- set_fact:
#    nginx_root: /usr/share/nginx/www
#  when: ansible_distribution == 'Debian'
#- apt: name=syslinux state=present
#- apt: name=dnsmasq state=present
#- apt: name=nginx state=present
#- file: path=/var/lib/tftpboot state=directory mode=755
#- file: path=/var/lib/netboot_images state=directory mode=755
#- command: tar xzvf /var/lib/netboot_images/amd64-trusty-installer.tar.gz -C /var/lib/tftpboot
#- template: src=var/lib/tftpboot/pxelinux.cfg/default dest=/var/lib/tftpboot/pxelinux.cfg/default mode=755
#- template: src=etc/dnsmasq.d/main.conf dest=/etc/dnsmasq.d/main.conf
#- template: src=etc/dnsmasq.d/mac_whitelist.conf dest=/etc/dnsmasq.d/mac_whitelist.conf
#- template: src=etc/init.d/dnsmasq dest=/etc/init.d/dnsmasq
#- service: name=dnsmasq state=restarted
#- template: src=usr/share/nginx/html/ks.cfg dest={{nginx_root}}/ks.cfg mode=755
