- apt: name=debootstrap state=present
- apt: name=linux-image-extra-{{target_kernel_version}}-generic state=present
- apt: name=nfs-kernel-server state=present
- file: path=/var/nfsroot state=directory mode=755
- file: path=/var/nfsroot/{{target_release}}-{{target_arch}} state=directory mode=755
- file: path=/var/lib/tftpboot/ubuntu-boot/{{target_release}}/{{target_arch}} state=directory mode=755
- template: src=etc/exports dest=/etc/exports mode=755
- command: /usr/sbin/exportfs -rv
- apt: name=linux-image-extra-{{target_kernel_version}}-generic
- copy: src=/boot/vmlinuz-{{target_kernel_version}}-generic dest=/var/lib/tftpboot/ubuntu-boot/{{target_release}}/{{target_arch}}
- copy: src=/etc/initramfs-tools dest=/tmp
- copy: src=initramfs-tools/modules dest=/tmp/initramfs-tools
- copy: src=initramfs-tools/initramfs.conf dest=/tmp/initramfs-tools
- command: mkinitramfs -o /var/lib/tftpboot/ubuntu-boot/{{target_release}}/{{target_arch}}/initramfs -c /tmp/initramfs-tools {{target_kernel_version}}-generic
- command: /usr/sbin/debootstrap --arch={{target_arch}} {{target_release}} /var/nfsroot/{{target_release}}-{{target_arch}}
- file: path=/var/nfsroot/{{target_release}}-{{target_arch}}/root/.ssh mode=600 state=directory
- copy: src=/root/.ssh/id_rsa.pub dest=/var/nfsroot/{{target_release}}-{{target_arch}}/root/.ssh/authorized_keys mode=600
- command: /usr/sbin/chroot /var/nfsroot/{{target_release}}-{{target_arch}} /usr/bin/apt-get update
- command: /usr/sbin/chroot /var/nfsroot/{{target_release}}-{{target_arch}} /usr/bin/apt-get install -y openssh-server
